{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  HOST_RABBIT: {{ .Values.config.credentials.amqp.host | default "cloudkitty" | b64enc }}
  USER_RABBIT: {{ .Values.config.credentials.amqp.user | default "cloudkitty" | b64enc }}
  PASSWORD_RABBIT: {{ .Values.config.credentials.amqp.password | default "cloudkitty" | b64enc }}
  HOST_DB: {{ .Values.config.credentials.sql.host | default "cloudkitty" | b64enc }}
  USER_DB: {{ .Values.config.credentials.sql.user | default "cloudkitty" | b64enc }}
  PASSWORD_DB: {{ .Values.config.credentials.sql.password | default "cloudkitty" | b64enc }}
  DATABASE_DB: {{ .Values.config.credentials.sql.database | default "cloudkitty" | b64enc }}
  HOST_BACKEND: {{ .Values.config.credentials.timeseries.host | default "cloudkitty" | b64enc }}
  USER_BACKEND: {{ .Values.config.credentials.timeseries.user | default "cloudkitty" | b64enc }}
  PASSWORD_BACKEND: {{ .Values.config.credentials.timeseries.password | default "cloudkitty" | b64enc }}
  HOST_PROMETHEUS: {{ .Values.config.credentials.prometheus.host | default "http://prometheus.openfaas.svc.cluster.local/api/v1" | b64enc }}
  HOST_CACHE: {{ .Values.config.credentials.cache.host | default "test-cloudkitty-redis-headless.cloudkitty.svc.cluster.local" | b64enc }}
  USER_CACHE: {{ .Values.config.credentials.cache.user | default "redis" | b64enc }}
  PASSWORD_CACHE: {{ .Values.config.credentials.cache.password | default "cloudkitty" | b64enc }}
{{- end }}