dependencies:
  - name: influxdb
    version: 3.0.2
    repository: "@stable"
    condition: influxdb.enabled,global.influxdb.enabled
  - name: redis
    version: 10.2.1
    repository: "@stable"
    condition: redis.enabled,global.redis.enabled
  - name: mariadb
    version: 7.3.1
    repository: "@stable"
    condition: mariadb.enabled,global.mariadb.enabled
  - name: rabbitmq
    version: 6.15.0
    repository: "@stable"
    condition: rabbitmq.enabled,global.rabbitmq.enabled
  - name: cloudkitty-processor
    version: 0.1.0
    repository: "file://charts/cloudkitty-processor"
    condition: cloudkitty-processor.enabled,global.cloudkitty-processor.enabled
  - name: cloudkitty-api
    version: 0.1.0
    repository: "file://charts/cloudkitty-api"
    condition: cloudkitty-api.enabled,global.cloudkitty-api.enabled