# Default values for cloudkitty-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: aimbot31/cloudkitty-api
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: "cloudkitty-api"
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: ['/']

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

config:
  enabled: true
  name: cloudkitty-api-config
  credentials:
    sql:
      host: test-cloudkitty-mariadb.cloudkitty.svc.cluster.local
      user: "cloudkitty"
      password: "cloudkitty"
      database: "cloudkitty"
    timeseries:
      host: test-cloudkitty-influxdb.cloudkitty.svc.cluster.local
      user: "cloudkitty"
      password: "cloudkitty"
    amqp:
      host: test-cloudkitty-rabbitmq.cloudkitty.svc.cluster.local
      user: "cloudkitty"
      password: "cloudkitty"


secret:
  enabled: true
  name: cloudkitty-api-secret

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
