{{- if .Values.config.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ .Release.Namespace }}
data:
  cloudkitty.conf: |-
    [DEFAULT]
    debug = true
    transport_url = rabbit://$USER_RABBIT:$PASSWORD_RABBIT@$HOST_RABBIT/
    auth_strategy = noauth

    [database]
    connection = mysql+pymysql://$USER_DB:$PASSWORD_DB@$HOST_DB/$DATABASE_DB

    [storage]
    backend = influxdb
    version = 2

    [storage_influxdb]
    username = $USER_BACKEND
    password = $PASSWORD_BACKEND
    database = cloudkitty
    host = $HOST_BACKEND
    retention_policy = "rp_365d"
  api_paste.ini: |-
    [pipeline:cloudkitty+noauth]
    pipeline = cors http_proxy_to_wsgi request_id ck_api

    [pipeline:cloudkitty+keystone]
    pipeline = cors http_proxy_to_wsgi request_id authtoken ck_api

    [app:ck_api]
    paste.app_factory = cloudkitty.api.app:app_factory

    [filter:authtoken]
    acl_public_routes = /, /v1
    paste.filter_factory = cloudkitty.api.middleware:AuthTokenMiddleware.factory

    [filter:request_id]
    paste.filter_factory = oslo_middleware:RequestId.factory

    [filter:cors]
    paste.filter_factory =  oslo_middleware.cors:filter_factory
    oslo_config_project = cloudkitty

    [filter:http_proxy_to_wsgi]
    paste.filter_factory = oslo_middleware.http_proxy_to_wsgi:HTTPProxyToWSGI.factory
    oslo_config_project = cloudkitty
{{- end }}