apiVersion: v1
data:
  cloudkitty.conf: |-
    [DEFAULT]
    debug = true
    transport_url = rabbit://guest:guest@rabbitmq/
    auth_strategy = no_auth

    [database]
    connection = mysql+pymysql://cloudkitty:ckdbpass@mariadb/cloudkitty

    [storage]
    backend = influxdb
    version = 2

    [storage_influxdb]
    username = cloudkitty
    password = cloudkitty
    database = cloudkitty
    host = influxdb
kind: ConfigMap
metadata:
  creationTimestamp: "2019-08-05T12:42:05Z"
  name: cloudkitty.conf
  namespace: cloudkitty
