apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ .Release.Namespace }}
data:
  cloudkitty.conf: |-
    [DEFAULT]
    debug = true
    transport_url = rabbit://$USER_RABBIT:$PASSWORD_RABBIT@rabbitmq/
    auth_strategy = noauth

    [database]
    connection = mysql+pymysql://$USER_DB:$PASSWORD_DB@mariadb/cloudkitty

    [storage]
    backend = influxdb
    version = 2

    [storage_influxdb]
    username = $USER_BACKEND
    password = $PASSWORD_BACKEND
    database = cloudkitty
    host = influxdb