{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  USER_RABBIT: YWRtaW4=
  PASSWORD_RABBIT: cGFzcw==
  USER_DB: YWRtaW4=
  PASSWORD_DB: cGFzcGFzcw==
  USER_BACKEND: YWRtaW4=
  PASSWORD_BACKEND: cGFzcGFzc3BhcnRvdXQ=
{{- end }}